version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: teddy_finance_db
    environment:
      POSTGRES_DB: teddy_finance
      POSTGRES_USER: teddy_user
      POSTGRES_PASSWORD: teddy_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - teddy_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: teddy_finance_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@teddy.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - teddy_network

volumes:
  postgres_data:

networks:
  teddy_network:
    driver: bridge