name: CI Checks

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main, develop]

env:
  NODE_VERSION: '22.17.0'

jobs:
  setup-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Verify Jest installation
        run: npx jest --version

      - name: Type check
        run: npm run typecheck

      - name: Run unit tests
        run: npm run test

      - name: Run unit tests with coverage
        run: npm run test:cov
